name = "BEE4750FinalProject"
uuid = "12345678-1234-1234-1234-123456789012"
authors = ["Your Name <your.email@cornell.edu>"]
version = "0.1.0"

[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
HiGHS = "1.20.1"
JuMP = "1.29.3"
julia = ">=1.6"
