name = "BEE4750FinalProject"
uuid = "12345678-1234-1234-1234-123456789012"
authors = ["Your Name <your.email@cornell.edu>"]
version = "0.1.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f2afa"

[targets]
test = ["Test"]
